version: 1.5.0.{build}
skip_tags: true
configuration: Debug
build:
  project: TerminologyLauncher/TerminologyLauncher.csproj
  verbosity: normal
test: off
artifacts:
- path: '*.zip'
nuget:
  account_feed: true
  project_feed: true