version: 1.0.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Debug
before_build:
  - nuget restore
build:
  project: TerminologyLauncher[DEBUG]/TerminologyLauncher[DEBUG].csproj
  verbosity: normal
test: off
nuget:
  account_feed: true
  project_feed: true