version: 1.5.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Debug
before_build:
  - nuget restore
build:
  project: TerminologyLauncher.sln
  verbosity: normal
test: off
artifacts:
- path: '*.zip'
nuget:
  account_feed: true
  project_feed: true